# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
print('The dimension (number of axes) of the Matrix A are: ', A.ndim)
print('The shape of the Matrix A are: ', A.shape)
print('The size of the Matrix A are: ', A.size)
print('The datatype of the Matrix A are: ', A.dtype)

The dimension (number of axes) of the Matrix A are:  2
The shape of the Matrix A are:  (3, 5)
The size of the Matrix A are:  15
The datatype of the Matrix A are:  int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
print('Result of elementwise subtraction (B-C):')
print(B-C)
print()
print('Result of elementwise multiplication (B*C):')
print(B*C)
print()
print('Result of Matrix multiplikation (B*C):')
print(B@C)

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print('Result if we exponentiate each number elementwise:')
print(np.exp(B))
print()
print('The minimum value of the whole matrix is: ', np.min(B))
print()
print('The minimum value in each row is: ', np.min(B, axis=0))
print()
print('The minimum value in each column is: ', np.min(B, axis=1))
print()
print('The minimum index value in the whole matrix is: ', np.argmin(B))
print()
print('The minimum index value in each row is: ', np.argmin(B, axis=0))
print()
print('Result of the sum for all elements: ', np.sum(B))
print()
print('Result of the mean for each column: ', np.mean(B, axis=1))
print()
print('Result of the median for each column: ', np.median(B, axis=1))

Result if we exponentiate each number elementwise:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

The minimum value of the whole matrix is:  1

The minimum value in each row is:  [1 2 3]

The minimum value in each column is:  [1 4 7]

The minimum index value in the whole matrix is:  0

The minimum index value in each row is:  [0 0 0]

Result of the sum for all elements:  45

Result of the mean for each column:  [2. 5. 8.]

Result of the median for each column:  [2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [7]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [9]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices. A[1] the second row. Equivalent to A[1, :]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
for element in A.ravel():
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [13]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [14]:
# On the first line we create a NumPy array 'a' with 30 consecutive numbers starting from 0. 
# It's a 1D array.
# The second line reshapes the original array 'a' into a new array 'b' with a new shape.
# 'b' is reshaped into a 3D array with dimensions 2x3x5.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]
(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [16]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [17]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print()

print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [18]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [19]:
def add_mult_matrices(matrix1, matrix2, operation):

    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise TypeError('Matrices must be numpy arrays.')
        
    if operation == 'add':
        if not matrix1.shape == matrix2.shape:
            raise ValueError ('To do matrix addition the matrices have to have the same shape.')
        else:
            return matrix1 + matrix2
        
    elif operation == 'multiply':
        if not matrix1.shape[1] == matrix2.shape[0]:
            raise ValueError ('To multiply to matrices columns and rows must be the same lenght.')
        else:
            return matrix1 @ matrix2
        
    else:
        raise Exception('The operation argument has to be "add" or "multiply"')

In [20]:
# B-2A
add_mult_matrices(B, -2*A, 'add')

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [21]:
# 3C-E
add_mult_matrices(3*C, -E, 'add')

ValueError: To do matrix addition the matrices have to have the same shape.

In [22]:
# AC
add_mult_matrices(A, C, 'multiply')

ValueError: To multiply to matrices columns and rows must be the same lenght.

In [23]:
# CD
add_mult_matrices(C, D, 'multiply')

array([[11, 10],
       [10, 11]])

In [24]:
# CB
add_mult_matrices(C, B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [25]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [26]:
print('AB:', add_mult_matrices(A, B, 'multiply'))
print()
print('AC:', add_mult_matrices(A, C, 'multiply'))
print()
print('AB = AC is ', (A@B == A@C).all())
print()
print('B = C is ', (B == C).all())  

AB: [[ 4  7]
 [ 8 14]]

AC: [[ 4  7]
 [ 8 14]]

AB = AC is  True

B = C is  False


**Chap2. Question 3**

In [27]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [28]:
print('AD:', '\n', add_mult_matrices(A, D, 'multiply'))
print()
print('and')
print()
print('DA:', '\n', add_mult_matrices(D, A, 'multiply'))

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

and

DA: 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [29]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

In [30]:
print('AB:', '\n', add_mult_matrices(A, B, 'multiply'))

AB: 
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [31]:
M1 = np.array([[5, 6], [4, 5]])
M2 = np.array([[6, 4], [3, 3]])

In [32]:
M1_inv = np.linalg.inv(M1)
print('The inverse of M1 is: ')
print(M1_inv)
print()
print(np.allclose(M1 @ M1_inv, np.eye(2)))
print()
M2_inv = np.linalg.inv(M2)
print('The inverse of M2 is: ')
print(M2_inv)
print()
print(np.allclose(M2 @ M2_inv, np.eye(2)))

The inverse of M1 is: 
[[ 5. -6.]
 [-4.  5.]]

True

The inverse of M2 is: 
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]

True


**Quiz p.19, Question 3**

In [33]:
A = np.array([[2, 2], [1, 2]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [34]:
M1 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
M2 = np.array([-7, 5, 2])
print(M1)
print()
print(M2)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[-7  5  2]


In [35]:
x = np.linalg.solve(M1, M2)
print(x)

[ 3.  4. -6.]


In [36]:
M1 @ x

array([-7.,  5.,  2.])

**Chap10. Question 1 b)**

In [37]:
M3 = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
M4 = np.array([1, -1, 1])
print(M3)
print()
print(M4)

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

[ 1 -1  1]


In [38]:
x = np.linalg.solve(M3, M4)
print(x)

[ 8.  2. -1.]


**Chap 12. Question 1**

In [39]:
M5 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

In [40]:
M5_inv = np.linalg.inv(M5)
print(M5_inv)
print()
print(np.allclose(M5 @ M5_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]

True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [41]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [42]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [43]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
